// See LICENSE.txt for license details.

#ifndef POURLOGIC_FLOW_METER_H
#define POURLOGIC_FLOW_METER_H

#include <Arduino.h>
#include "config.h"

/*! \brief Manages a flow meter who pulses on a digital input pin during flow.
 *  This class provides an interface to an interupt-based flow meter where the
 *  frequency of the pulses can be converted to a volumetric flow rate. This
 *  volumetric flow rate is then integrated to provide a volume.
 *
 *  Written for the G1/2 flow sensor from seeedstudio.com (POW110D3B) but
 *  should work with other interrupt-based flow meters.
 *
 *  *** 
 *
 *  We use a flow meter for determining the total volume that flowed
 *  during an arbitrary interval. To determine the volumetric flow rate,
 *  numerical mehods must be employed. However, for the total volume,
 *  the math involved is much simpler. The total volume is proportional to
 *  the number of pulses counted. See #calibrate for more details.
 *
 *  Calibrating your flow meter is recommended. Do this by allowing
 *  liquid to flow through the flow meter. Collect this liquid for
 *  measurement. Count the number of pulses generated by the flow meter
 *  during the flow. The value of interested is computed by the
 *  following formula:
 *                           k = V / C
 * 
 *  You can run this calibration a number of times to find the average
 *  value (if you're feeling so keen).
 *
 *  In the future, calibration can be performed and the pulse count will
 *  either be displayed on an LCD (if memory permits) or sent to the
 *  server where it can be combined with the poured volume to find k where
 *  it can then be (down-)synched on, say, startup.
 *
 *  \see #calibrate
 *  \see http://www.seeedstudio.com/depot/g12-water-flow-sensor-p-635.html
 */
class FlowMeter {

  private:
    unsigned long _pulseCount; //!< Accumulates when flow meter pulses on #_interruptPin when interrupts are attached and enabled
    int _interruptPin; //!< The input pin attached to the flow meter's output
    int _interruptNumber; //!< The interrupt number used for the flow meter
    
    void _startReading(); //!< Attach #_interruptPin to #pulse() using #_interruptNumber and set current flow meter to this instance
    void _stopReading(); //!< Detach interrupts and clear the current flow meter reference
    
  public:
    FlowMeter(){ /**/ }
    ~FlowMeter(){ /**/ }
    
    //!< Sets up the flow meter pins, etc.
    void begin(int interruptPin, int interruptNumber);
    
    //!< Read flowed volume in mL until a maximum volume is reached, a given time since the meter read flow has passed, and/or a total time has passed
    float readVolume_mL(int maxVolume_mL, unsigned long lastPulseTimeout_ms = 1000, unsigned long totalTimeout_ms = 5000, unsigned long delay_ms = 250);

    //!< Will return the pulse count from first pulse.
    unsigned long calibrate(unsigned long pourtime_ms = 1000, unsigned long timeout_ms = 5000);
    
    //!< Interrupt handler for a flow meter pulse.
    static void pulse();
};

#endif

